rank4_cron_check:
  services:
    - name: rank4_sched_815
      spec: '@every 500s'
      bin: rank4_sched_815
      path: /data/rank4-sched-815/approot/tools
    - name: rank4_sched_801
      spec: '@every 300s'
      bin: rank4_sched_801
      path: /data/rank4-sched-801/approot/tools
    - name: rank4_sched_809
      spec: '*/10 * * * *'
      bin: rank4_sched_809
      path: /data/rank4-sched-809/approot/tools
    - name: rank4_sched_810
      spec: '*/10 * * * *'
      bin: rank4_sched_810
      path: /data/rank4-sched-810/approot/tools



