rank4_cron_check:
  services:
    - name: rank4_sched_815
      spec: '@every 5s'
      bin: rank4_sched_815
      path: /data/rank4-sched-815/approot/tools
    - name: comm_801
      spec: '*/1 * * * *'
      bin: rank4_sched_801
      path: /data/rank4-sched-801/approot/tools
